controllers:
    resource: ../src/Controller/
    type: attribute
mail:
    path: /mail
    controller: App\Controller\MailController::index
    methods: [GET, POST]
api_login_check:
    path: /api/login_check